Repository iamakashrout/Social-Media-Application, pull requests merged in 2025-04, with the labels that each got.

#61 added a stories feature
  backend/app.js
  backend/controllers/storyController.js
  backend/models/storyModel.js
  backend/routes/storyRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Stories/CreateStory.css
  frontend/src/components/Stories/CreateStory.jsx
  frontend/src/components/Stories/CreateStoryButton.css
  frontend/src/components/Stories/CreateStoryButton.jsx
  frontend/src/components/Stories/Stories.css
  frontend/src/components/Stories/Stories.jsx
  frontend/src/components/Stories/ViewStoriesButton.css
  frontend/src/components/Stories/ViewStoriesButton.jsx
  frontend/src/components/homepage.jsx
Labels: pwoc, hard

#64 Updated README issue #62
  README.md
Labels: pwoc, easy

#66 engaging posts
  backend/.gitignore
  backend/app.js
  backend/controllers/postControllers.js
  backend/models/postModel.js
  backend/routes/postRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/MyPost.jsx
  frontend/src/components/PostWidget.jsx
  frontend/src/components/Posts.jsx
  frontend/src/components/homepage.jsx
Labels: pwoc, medium
