Repository iamakashrout/Social-Media-Application, pull requests merged in 2025-03, with the labels that each got.

#18 I have tried my best to change the UI.
  frontend/src/components/Auth/auth.css
  frontend/src/components/Auth/auth.jsx
  frontend/src/images/Untitled design (1).png
  frontend/src/images/home_background (1).png
  frontend/src/images/home_background.mp4
  frontend/src/images/home_background.png
  frontend/src/images/home_bg.png
  frontend/src/images/home_bg_2.png
Labels: pwoc, easy

#19 added edit/delete/like functionality in comments
  backend/controllers/postControllers.js
  backend/models/postModel.js
  backend/public/assets/Screenshot 2025-02-28 225903.png
  backend/routes/postRoutes.js
  frontend/src/components/PostWidget.jsx
Labels: pwoc, medium

#20 Issue Resolved #12: Added Forgot Password with OTP verification
  backend/app.js
  backend/controllers/authControllers.js
  backend/models/forgotpassword.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/Auth/ForgotPassword.css
  frontend/src/components/Auth/ForgotPassword.jsx
  frontend/src/components/Auth/ResetPassword.css
  frontend/src/components/Auth/ResetPassword.jsx
  frontend/src/components/Auth/VerifyOtp.css
  frontend/src/components/Auth/VerifyOtp.jsx
  frontend/src/components/Auth/auth.jsx
Labels: pwoc, medium

#21 Issue#11 resolved. User Verification during register added
  backend/controllers/authControllers.js
  backend/models/userModel.js
  backend/routes/authRoutes.js
  frontend/src/App.js
  frontend/src/components/Auth/ForgotPassword.jsx
  frontend/src/components/Auth/VerifyOtpRegister.css
  frontend/src/components/Auth/VerifyOtpRegister.jsx
  frontend/src/components/Auth/auth.jsx
Labels: pwoc, medium

#23 Issue#22 resolved: User can register without uploading picture done
  backend/app.js
  backend/controllers/authControllers.js
  backend/models/userModel.js
  backend/uploads/default_profile_image.png
  frontend/src/components/Auth/auth.jsx
  frontend/src/components/ProfilePage.jsx
  frontend/src/components/homepage.jsx
Labels: pwoc, easy

#24 Edit Profile Page addded
  backend/controllers/usersControllers.js
  backend/middleware/firebase_config.js
  backend/package-lock.json
  backend/package.json
  backend/routes/usersRoutes.js
  frontend/src/App.js
  frontend/src/components/EditProfile.jsx
  frontend/src/components/ProfilePage.jsx
Labels: pwoc, easy

#30 added delete post functionality
  backend/app.js
  backend/controllers/postControllers.js
  backend/public/assets/download (1).jpeg
  backend/public/assets/download (2).jpeg
  backend/public/assets/images.jpeg
  backend/routes/postRoutes.js
  frontend/src/components/PostWidget.jsx
  frontend/src/helper.js
  frontend/src/state/index.js
Labels: pwoc, easy

#33 Solved #32 : Dockerized the Application
  backend/.dockerignore
  backend/Dockerfile
  backend/app.js
  docker-compose.yaml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/package.json
Labels: pwoc, medium

#35 Search functionality updated
  backend/controllers/usersControllers.js
  frontend/src/components/SearchPage.jsx
  frontend/src/components/navbar.jsx
Labels: pwoc, medium

#36 implemented chatbot using gemini
  backend/app.js
  backend/controllers/gemini/context.js
  backend/controllers/gemini/geminiController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/chatbotRoutes.js
  frontend/src/components/Chatbot/HelpButton.css
  frontend/src/components/Chatbot/HelpButton.jsx
  frontend/src/components/Chatbot/HelpChat.css
  frontend/src/components/Chatbot/HelpChat.jsx
  frontend/src/components/homepage.jsx
  frontend/src/helper.js
Labels: pwoc, hard

#38 added voice to speech option in chatbot
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Chatbot/HelpChat.css
  frontend/src/components/Chatbot/HelpChat.jsx
  frontend/src/components/Chatbot/voicespeech.jsx
Labels: pwoc, medium

#40 #34 : Shifted Media Storage to Cloudinary
  backend/package-lock.json
  frontend/src/components/Auth/auth.jsx
  frontend/src/components/EditProfile.jsx
  frontend/src/components/MyPost.jsx
Labels: pwoc, medium

#42 Pre fill fields set for edit profile
  frontend/src/components/EditProfile.jsx
Labels: pwoc, easy

#43 added text to speech feature for each response from chatbot
  backend/controllers/gemini/geminiController.js
  frontend/package.json
  frontend/src/components/Chatbot/HelpChat.css
  frontend/src/components/Chatbot/HelpChat.jsx
Labels: pwoc, hard

#46 Added notification feature
  backend/app.js
  backend/controllers/notif/addNotifController.js
  backend/controllers/notif/postNotifsControllers.js
  backend/controllers/postControllers.js
  backend/controllers/usersControllers.js
  backend/models/notifsModel.js
  backend/routes/notifsRoutes.js
  frontend/src/components/Notifications.jsx
  frontend/src/components/NotificationsPopup.jsx
  frontend/src/components/Posts.jsx
  frontend/src/components/navbar.jsx
  frontend/src/helper.js
Labels: pwoc, hard

#50 Solved #48 : Allowed feature to show posts made by friends only
  frontend/src/components/Posts.jsx
Labels: pwoc, easy

#51 Implemented Persistent Login Feature issue #47
  backend/controllers/usersControllers.js
  backend/routes/notifsRoutes.js
  frontend/src/App.js
  frontend/src/components/Auth/auth.jsx
  frontend/src/components/navbar.jsx
  frontend/src/state/index.js
Labels: pwoc, medium

#53 Text highlighter and pause button added
  frontend/src/components/Chatbot/HelpChat.css
  frontend/src/components/Chatbot/HelpChat.jsx
Labels: pwoc, medium

#54 implemented caching user data
  .gitignore
  backend/controllers/usersControllers.js
  backend/package-lock.json
  backend/package.json
Labels: pwoc, hard

#57 Add voice search in search bar issue #52
  frontend/src/components/navbar.jsx
  frontend/src/components/voice search in search bar.jsx
Labels: pwoc, medium

#58 implemented caching of prev searches made by user
  backend/controllers/usersControllers.js
  backend/routes/usersRoutes.js
  frontend/src/components/navbar.jsx
Labels: pwoc, hard
